export const CREATE_USER = '@@USER_LIST/CREATE_USER';
export const UPDATE_USER = '@@USER_LIST/UPDATE_USER';
export const GET_USERS = '@@USER_LIST/GET_USERS';
export const DELETE_USER = '@@USER_LIST/DELETE_USER';
export const SORT_USER_BY = '@@USER_LIST/SORT_USER_BY';
export const GET_FILTERED_USERS = '@@USER_LIST/GET_FILTERED_USERS';
